// Package routegen turns the .gox files under a pages directory into a
// typed Go file. After running, application code can write
// routes.Blog.Slug("hello") instead of "/blog/" + slug, and a typo
// becomes a compile error rather than a 404 at runtime.
//
// Generation is deterministic: the same input directory always
// produces byte-identical output, which keeps reproducible builds
// honest and makes diffs reviewable.
package routegen

import (
	"bytes"
	"fmt"
	"os"
	"path/filepath"
	"sort"
	"strings"

	"github.com/dev2k6/Nguyen.go/internal/router"
)

// Options controls a generation run.
type Options struct {
	PagesDir   string // root of .gox routes
	OutputPath string // path of the .gen.go file to write
	Package    string // package name in the generated file
}

// Generate writes a Go file containing typed accessors for every route
// discovered under opts.PagesDir. It returns the number of routes
// emitted and any I/O error.
func Generate(opts Options) (int, error) {
	if opts.Package == "" {
		opts.Package = "routes"
	}
	routes, err := router.Discover(opts.PagesDir)
	if err != nil {
		return 0, fmt.Errorf("routegen: discover: %w", err)
	}

	sort.Slice(routes, func(i, j int) bool {
		return routes[i].Pattern < routes[j].Pattern
	})

	var src bytes.Buffer
	src.WriteString("// Code generated by nguyen generate routes. DO NOT EDIT.\n")
	src.WriteString("// Run \"nguyen generate routes\" to refresh after adding pages.\n\n")
	src.WriteString("package " + opts.Package + "\n\n")
	src.WriteString("import \"strings\"\n\n")

	src.WriteString("// All is the canonical list of route patterns discovered at codegen time.\n")
	src.WriteString("var All = []string{\n")
	for _, r := range routes {
		if r.Is404 {
			continue
		}
		fmt.Fprintf(&src, "\t%q,\n", r.Pattern)
	}
	src.WriteString("}\n\n")

	emitted := 0
	for _, r := range routes {
		if r.Is404 {
			continue
		}
		emitRouteFunc(&src, r)
		emitted++
	}

	emitJoin(&src)

	if err := os.MkdirAll(filepath.Dir(opts.OutputPath), 0o755); err != nil {
		return 0, fmt.Errorf("routegen: mkdir: %w", err)
	}
	if err := os.WriteFile(opts.OutputPath, src.Bytes(), 0o644); err != nil {
		return 0, fmt.Errorf("routegen: write: %w", err)
	}
	return emitted, nil
}

func emitRouteFunc(out *bytes.Buffer, r router.Route) {
	name := funcName(r)
	params := dynamicParams(r)

	fmt.Fprintf(out, "// %s returns the URL for %q.\n", name, r.Pattern)
	if len(params) == 0 {
		fmt.Fprintf(out, "func %s() string { return %q }\n\n", name, r.Pattern)
		return
	}

	out.WriteString("func " + name + "(")
	for i, p := range params {
		if i > 0 {
			out.WriteString(", ")
		}
		fmt.Fprintf(out, "%s string", p)
	}
	out.WriteString(") string {\n")

	out.WriteString("\treturn join(\"/\",\n")
	for _, seg := range r.Segments {
		switch seg.Type {
		case router.Static:
			if seg.Name == "index" {
				continue
			}
			fmt.Fprintf(out, "\t\t%q,\n", seg.Name)
		case router.Dynamic:
			fmt.Fprintf(out, "\t\t%s,\n", seg.ParamName)
		case router.CatchAll, router.Optional:
			fmt.Fprintf(out, "\t\t%s,\n", seg.ParamName)
		}
	}
	out.WriteString("\t)\n}\n\n")
}

func dynamicParams(r router.Route) []string {
	var out []string
	seen := map[string]bool{}
	for _, seg := range r.Segments {
		switch seg.Type {
		case router.Dynamic, router.CatchAll, router.Optional:
			if !seen[seg.ParamName] {
				out = append(out, seg.ParamName)
				seen[seg.ParamName] = true
			}
		}
	}
	return out
}

func funcName(r router.Route) string {
	if r.Pattern == "/" {
		return "Index"
	}
	parts := strings.Split(strings.Trim(r.Pattern, "/"), "/")
	var sb strings.Builder
	for _, p := range parts {
		clean := p
		if strings.HasPrefix(p, ":") {
			clean = "by_" + p[1:]
		}
		if p == "*" {
			clean = "wildcard"
		}
		clean = strings.ReplaceAll(clean, "-", "_")
		clean = strings.ReplaceAll(clean, ".", "_")
		sb.WriteString(toExported(clean))
	}
	return sb.String()
}

func toExported(s string) string {
	if s == "" {
		return ""
	}
	parts := strings.Split(s, "_")
	var sb strings.Builder
	for _, p := range parts {
		if p == "" {
			continue
		}
		sb.WriteString(strings.ToUpper(p[:1]))
		if len(p) > 1 {
			sb.WriteString(p[1:])
		}
	}
	return sb.String()
}

func emitJoin(out *bytes.Buffer) {
	out.WriteString(`// join concatenates segments with sep, skipping empty values.
func join(sep string, parts ...string) string {
	kept := parts[:0]
	for _, p := range parts {
		if p != "" {
			kept = append(kept, p)
		}
	}
	return sep + strings.Join(kept, sep)
}
`)
}
